### ISSUE TITLE
[BUG]5月3日新版的文件运行后   文字生成图片报错     for i in r【'images'】:    KeyError: 'images'

### ISSUE THREAD

**Issue by lhtpluto** [LemonQu-GIT/ChatGLM-6B-Engineering#12]
**Describe the bug**
新版的文件运行后   文字生成图片报错     for i in r【'images'】:    KeyError: 'images'

**To Reproduce**
1. 选择 'Stable Diffusion'
2. 输入提示文字
3. 点击发送
4. 报错for i in r【'images'】:    KeyError: 'images'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Version  win11
 - CUDA 11.8

**Additional context**

-================================

问题确认了，不是BUG  与程序无关

1. 是本地环境异常  CUDA Toolkit  需要重新安装；
2. sd-webui-aki-v4 运行异常， 修改Cross-Attention后恢复正常（放弃使用xFormers）

**Comment by LQDWJY** [comment]
https://raw.githubusercontent.com/LemonQu-GIT/ChatGLM-6B-Engineering/main/streamlit_utils.py
若继续使用原版的该程序文件情况是怎样的呢？柠檬貌似没有改stable diffusion的东西

**Comment by lhtpluto** [comment]
问题确认了，与程序无关

1. 是本地环境异常  CUDA Toolkit  需要重新安装；
2. sd-webui-aki-v4 运行异常， 修改Cross-Attention后恢复正常（放弃使用xFormers）

**Comment by LQDWJY** [comment]
好的，感谢反馈
