### ISSUE TITLE
Loading caption model blip-large

### ISSUE THREAD

**Issue by withyou971** [LemonQu-GIT/ChatGLM-6B-Engineering#16]
总是停在这里，请问下需要去huggingface下载哪个模型，放在什么位置，谢谢

**Comment by LQDWJY** [comment]
如果存在其它模型权重需要下载请保证网络通畅

**Comment by withyou971** [comment]
谢谢，我用的wsl ubt下的环境，没有找到sam.py，只有pipeline_stable_diffusion_pix2pix_zero.py这个文件里面有，
from transformers import (
    BlipForConditionalGeneration,
    BlipProcessor,
    CLIPImageProcessor,
    CLIPTextModel,
    CLIPTokenizer,
)但是注释了以后好像没用

**Comment by LQDWJY** [comment]
如果不是这个模块调用的话，就只能使用魔法，保证网络通畅的情况下，进行相关的权重的下载了，如果有能力的话，可以去from_pretrain()函数下依次去查看最终指向的网址，或者是在下载时打印出来的下载地址，然后再去下载。相关的查看思路网上有例子，可以去看看。
