### ISSUE TITLE
[BUG]SD API return

### ISSUE THREAD

**Issue by shadowzz624** [LemonQu-GIT/ChatGLM-6B-Engineering#9]
API error: POST: http://127.0.0.1:7861/sdapi/v1/txt2img {'error': 'TypeError', 'detail': '', 'body': '', 'errors': "'<' not supported between instances of 'int' and 'NoneType'"}
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /home/shadowzz/stable-diffusion-webui/myenv/lib/python3.10/site-packages/anyio/streams/memory.py:94 in receive       │
│                                                                                                                      │
│ /home/shadowzz/stable-diffusion-webui/myenv/lib/python3.10/site-packages/anyio/streams/memory.py:89 in               │
│ receive_nowait                                                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
WouldBlock

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /home/shadowzz/stable-diffusion-webui/myenv/lib/python3.10/site-packages/starlette/middleware/base.py:78 in          │
│ call_next                                                                                                            │
│                                                                                                                      │
│ /home/shadowzz/stable-diffusion-webui/myenv/lib/python3.10/site-packages/anyio/streams/memory.py:114 in receive      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
EndOfStream

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /home/shadowzz/stable-diffusion-webui/modules/api/api.py:145 in exception_handling                                   │
│                                                                                                                      │
│   144 │   │   try:                                                                                                   │
│ ❱ 145 │   │   │   return await call_next(request)                                                                    │
│   146 │   │   except Exception as e:                                                                                 │
│                                                                                                                      │
│ ╭──────────────────────────────────────────── locals ────────────────────────────────────────────╮                   │
│ │        call_next = <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7fd689b6f010> │                   │
│ │                e = TypeError("'<' not supported between instances of 'int' and 'NoneType'")    │                   │
│ │ handle_exception = <function api_middleware.<locals>.handle_exception at 0x7fd689d375b0>       │                   │
│ │          request = <starlette.requests.Request object at 0x7fd6891d9600>                       │                   │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────────╯                   │
│                                                                                                                      │
│ /home/shadowzz/stable-diffusion-webui/myenv/lib/python3.10/site-packages/starlette/middleware/base.py:84 in          │
│ call_next                                                                                                            │
│                                                                                                                      │
│                                               ... 20 frames hidden ...                                               │
│                                                                                                                      │
│ /home/shadowzz/stable-diffusion-webui/modules/api/api.py:284 in text2imgapi                                          │
│                                                                                                                      │
│   283 │   │   if not self.default_script_arg_txt2img:                                                                │
│ ❱ 284 │   │   │   self.default_script_arg_txt2img = self.init_default_script_args(script_runne                       │
│   285 │   │   selectable_scripts, selectable_script_idx = self.get_selectable_script(txt2imgre                       │
│                                                                                                                      │
│ ╭──────────────────────────────── locals ─────────────────────────────────╮                                          │
│ │ script_runner = <modules.scripts.ScriptRunner object at 0x7fd760168190> │                                          │
│ │          self = <modules.api.api.Api object at 0x7fd605139ab0>          │                                          │
│ │    txt2imgreq = StableDiffusionProcessingTxt2Img(                       │                                          │
│ │                 │   enable_hr=False,                                    │                                          │
│ │                 │   denoising_strength=0,                               │                                          │
│ │                 │   firstphase_width=0,                                 │                                          │
│ │                 │   firstphase_height=0,                                │                                          │
│ │                 │   hr_scale=2.0,                                       │                                          │
│ │                 │   hr_upscaler=None,                                   │                                          │
│ │                 │   hr_second_pass_steps=0,                             │                                          │
│ │                 │   hr_resize_x=0,                                      │                                          │
│ │                 │   hr_resize_y=0,                                      │                                          │
│ │                 │   prompt='A bird, fly in the sky',                    │                                          │
│ │                 │   styles=None,                                        │                                          │
│ │                 │   seed=-1,                                            │                                          │
│ │                 │   subseed=-1,                                         │                                          │
│ │                 │   subseed_strength=0,                                 │                                          │
│ │                 │   seed_resize_from_h=-1,                              │                                          │
│ │                 │   seed_resize_from_w=-1,                              │                                          │
│ │                 │   sampler_name=None,                                  │                                          │
│ │                 │   batch_size=1,                                       │                                          │
│ │                 │   n_iter=1,                                           │                                          │
│ │                 │   steps=5,                                            │                                          │
│ │                 │   cfg_scale=7.0,                                      │                                          │
│ │                 │   width=512,                                          │                                          │
│ │                 │   height=512,                                         │                                          │
│ │                 │   restore_faces=False,                                │                                          │
│ │                 │   tiling=False,                                       │                                          │
│ │                 │   do_not_save_samples=False,                          │                                          │
│ │                 │   do_not_save_grid=False,                             │                                          │
│ │                 │   negative_prompt='',                                 │                                          │
│ │                 │   eta=None,                                           │                                          │
│ │                 │   s_churn=0.0,                                        │                                          │
│ │                 │   s_tmax=None,                                        │                                          │
│ │                 │   s_tmin=0.0,                                         │                                          │
│ │                 │   s_noise=1.0,                                        │                                          │
│ │                 │   override_settings=None,                             │                                          │
│ │                 │   override_settings_restore_afterwards=True,          │                                          │
│ │                 │   script_args=[],                                     │                                          │
│ │                 │   sampler_index='Euler',                              │                                          │
│ │                 │   script_name=None,                                   │                                          │
│ │                 │   send_images=True,                                   │                                          │
│ │                 │   save_images=False,                                  │                                          │
│ │                 │   alwayson_scripts={}                                 │                                          │
│ │                 )                                                       │                                          │
│ ╰─────────────────────────────────────────────────────────────────────────╯                                          │
│                                                                                                                      │
│ /home/shadowzz/stable-diffusion-webui/modules/api/api.py:241 in init_default_script_args                             │
│                                                                                                                      │
│   240 │   │   for script in script_runner.scripts:                                                                   │
│ ❱ 241 │   │   │   if last_arg_index < script.args_to:                                                                │
│   242 │   │   │   │   last_arg_index = script.args_to                                                                │
│                                                                                                                      │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮                                         │
│ │ last_arg_index = 1                                                       │                                         │
│ │         script = <prompt_matrix.py.Script object at 0x7fd689b64850>      │                                         │
│ │  script_runner = <modules.scripts.ScriptRunner object at 0x7fd760168190> │                                         │
│ │           self = <modules.api.api.Api object at 0x7fd605139ab0>          │                                         │
│ ╰──────────────────────────────────────────────────────────────────────────╯                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: '<' not supported between instances of 'int' and 'NoneType'
INFO:     127.0.0.1:60200 - "POST /sdapi/v1/txt2img HTTP/1.1" 500 Internal Server Error

**Comment by LemonQu-GIT** [comment]
请运行
```python webui.py --xformers --nowebui```
后使用 python 运行下列代码
```python
from PIL import Image, PngImagePlugin
import requests, io, base64
url = "http://127.0.0.1:7861"
payload = {
    "prompt": "A picture of a bird",
    "steps": 5,
    "negative_prompt": ""
}
response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload)
r = response.json()
for i in r['images']:
    image = Image.open(io.BytesIO(base64.b64decode(i.split(",",1)[0])))
    png_payload = {
        "image": "data:image/png;base64," + i
    }
    response2 = requests.post(url=f'{url}/sdapi/v1/png-info', json=png_payload)
    pnginfo = PngImagePlugin.PngInfo()
    pnginfo.add_text("parameters", response2.json().get("info"))
    image.save('stable_diffusion.png', pnginfo=pnginfo)
```
并查看返回结果

**Comment by shadowzz624** [comment]
3q，问题已解决









      发自我的企业微信         

 
 
 ----------Reply to Message----------
 On Mon, May 1, 2023 19:52 PM ***@***.***&gt; wrote:

  

 
请运行
 python webui.py --xformers --nowebui
 后使用 python 运行下列代码
 from PIL import Image, PngImagePlugin import requests, io, base64 url = "http://127.0.0.1:7861" payload = {     "prompt": "A picture of a bird",     "steps": 5,     "negative_prompt": "" } response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload) r = response.json() for i in r['images']:     image = Image.open(io.BytesIO(base64.b64decode(i.split(",",1)[0])))     png_payload = {         "image": "data:image/png;base64," + i     }     response2 = requests.post(url=f'{url}/sdapi/v1/png-info', json=png_payload)     pnginfo = PngImagePlugin.PngInfo()     pnginfo.add_text("parameters", response2.json().get("info"))     image.save('stable_diffusion.png', pnginfo=pnginfo)
 
并查看返回结果
